import React, { useMemo } from 'react';

export default function IssuerDetailModal({ data, onClose, onBondClick }) {
  if (!data) return null;
  const { issuer, bonds } = data;
  const issuerBonds = useMemo(() => bonds.filter(b => b.t === issuer.t).sort((a, b) => (b.nom || b.vol || 0) - (a.nom || a.vol || 0)), [issuer, bonds]);
  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-0 sm:p-4 bg-slate-900/60 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="issuer-modal-title">
      <div className="bg-white rounded-none sm:rounded-3xl shadow-2xl w-full max-w-4xl max-h-screen sm:max-h-[90vh] flex flex-col overflow-hidden border-0 sm:border border-slate-200">
        <div className="bg-slate-50 px-6 py-4 border-b border-slate-200 flex justify-between items-center shrink-0">
          <div className="flex items-center gap-3"><Flag c={issuer.co} className="w-8 h-5 shadow-sm" /><div><h3 id="issuer-modal-title" className="text-xl font-black text-slate-800 tracking-tight">{issuer.e}</h3><div className="flex items-center gap-2 mt-0.5"><span className="text-xs text-slate-500 font-mono font-bold bg-white px-1.5 py-0.5 rounded border border-slate-200">{issuer.t}</span><span className="text-xs font-medium text-slate-500">{CN[issuer.co] || issuer.co}</span></div></div></div>
          <button onClick={onClose} className="w-8 h-8 flex items-center justify-center rounded-full hover:bg-slate-200 transition-colors text-slate-500 text-xl" aria-label="Dialog schließen">✕</button>
        </div>
        <div className="p-6 overflow-y-auto flex-1 scrollbar-thin scrollbar-thumb-slate-200">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
            <div className="bg-slate-50 border border-slate-100 rounded-xl p-3"><p className="text-[10px] uppercase font-bold text-slate-400">Gesamtvolumen</p><p className="text-lg font-black text-slate-800 mt-1 tabular-nums">{fmtVol(issuer.nom)}</p></div>
            <div className="bg-slate-50 border border-slate-100 rounded-xl p-3"><p className="text-[10px] uppercase font-bold text-slate-400">Ø Rating</p><div className="mt-1"><Tag c={issuer.wLn >= 8 && issuer.wLn < 99 ? "gray" : "blue"}>{issuer.lo}</Tag></div></div>
            <div className="bg-slate-50 border border-slate-200 rounded-xl p-3"><p className="text-[10px] uppercase font-bold text-slate-500">Ø Rendite</p><p className="text-lg font-black text-slate-800 mt-1 tabular-nums">{fx(issuer.wY, 2)}%</p></div>
            <div className="bg-spark-50 border border-spark-100 rounded-xl p-3"><p className="text-[10px] uppercase font-bold text-spark-600/70">Ø I-Spread</p><p className="text-lg font-black text-spark-700 mt-1 tabular-nums">{fx(issuer.wS, 1)} bp</p></div>
            <div className="bg-slate-50 border border-slate-100 rounded-xl p-3"><p className="text-[10px] uppercase font-bold text-slate-400">Ø Duration</p><p className="text-lg font-bold text-slate-700 mt-1 tabular-nums">{fx(issuer.wD, 2)}</p></div>
            <div className="bg-slate-50 border border-slate-100 rounded-xl p-3"><p className="text-[10px] uppercase font-bold text-slate-400">Anzahl Anleihen</p><p className="text-lg font-bold text-slate-700 mt-1 tabular-nums">{issuer.count}</p></div>
            <div className="bg-slate-50 border border-slate-100 rounded-xl p-3 col-span-2"><p className="text-[10px] uppercase font-bold text-slate-400 mb-1">ESG Anteil (Volumen)</p><div className="flex items-center gap-3 mt-1"><span className="text-lg font-bold text-emerald-600 tabular-nums w-12">{fx(issuer.gP * 100, 0)}%</span><div className="flex-1 h-2 bg-slate-200 rounded-full overflow-hidden"><div className="h-full bg-emerald-500 rounded-full" style={{ width: `${issuer.gP * 100}%` }}></div></div></div></div>
            {(() => { const sek = issuerBonds[0]; return sek ? <div className="bg-slate-50 border border-slate-100 rounded-xl p-3 col-span-2"><p className="text-[10px] uppercase font-bold text-slate-400">Sektor / Branche</p><p className="text-sm font-bold text-slate-700 mt-1">{SEKTOR_LABELS[sek.sektor] || sek.sektor || "-"} {sek.branche ? `(${sek.branche})` : ""}</p></div> : null; })()}
          </div>
          <h4 className="text-[11px] uppercase font-black text-slate-800 tracking-widest mb-3 border-b border-slate-100 pb-2">Zugeordnete Anleihen im Kontext</h4>
          <div className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm">
            <table className="w-full text-[11px] sm:text-xs mobile-sticky-col">
              <thead className="bg-slate-50 border-b border-slate-200"><tr><th className="px-3 py-2.5 text-left text-slate-500 font-bold uppercase tracking-wider">ISIN</th><th className="px-3 py-2.5 text-right text-slate-500 font-bold uppercase tracking-wider">Volumen</th><th className="px-3 py-2.5 text-center text-slate-500 font-bold uppercase tracking-wider">Kupon</th><th className="px-3 py-2.5 text-center text-slate-500 font-bold uppercase tracking-wider">Preis</th><th className="px-3 py-2.5 text-center text-slate-500 font-bold uppercase tracking-wider">Laufzeit</th><th className="px-3 py-2.5 text-center text-slate-500 font-bold uppercase tracking-wider">Rendite</th><th className="px-3 py-2.5 text-center text-slate-500 font-bold uppercase tracking-wider">Spread</th><th className="px-3 py-2.5 text-center text-slate-500 font-bold uppercase tracking-wider">Rating</th><th className="px-3 py-2.5 text-center text-slate-500 font-bold uppercase tracking-wider">ESG</th><th className="px-3 py-2.5 text-center text-[10px] text-slate-500 font-bold uppercase tracking-wider">Rang</th><th className="px-3 py-2.5 text-center text-[10px] text-slate-500 font-bold uppercase tracking-wider">Typ</th></tr></thead>
              <tbody className="divide-y divide-slate-100">{issuerBonds.map(b => (<tr key={b.id} onClick={() => onBondClick(b)} className="hover:bg-spark-50 transition-colors cursor-pointer group"><td className="px-3 py-2 text-slate-700 font-mono group-hover:text-spark-600 transition-colors">{b.isin}</td><td className="px-3 py-2 text-right text-slate-800 font-bold tabular-nums bg-slate-50/50">{fmtVol(b.nom || b.vol)}</td><td className="px-3 py-2 text-center text-slate-600 tabular-nums">{fx(b.k, 2)}%</td><td className="px-3 py-2 text-center text-slate-600 tabular-nums">{b.px ? fx(b.px, 2) : "-"}</td><td className="px-3 py-2 text-center text-slate-600 tabular-nums">{fx(b.mty, 2)} Y</td><td className="px-3 py-2 text-center text-slate-800 font-bold tabular-nums">{fx(b.y, 2)}%</td><td className="px-3 py-2 text-center text-spark-600 font-bold tabular-nums">{fx(b.s, 1)}</td><td className="px-3 py-2 text-center"><Tag c={b.ln >= 8 ? "gray" : "blue"}>{b.lo}</Tag></td><td className="px-3 py-2 text-center">{b.g ? <Tag c="green">ESG</Tag> : <span className="text-slate-300">-</span>}</td><td className="px-3 py-2 text-center"><span className={"px-2 py-0.5 rounded-full text-[10px] font-bold " + rankBadgeCls(b.rank || "SP")}>{b.rank || "SP"}</span></td><td className="px-3 py-2 text-center"><span className={"px-2 py-0.5 rounded-full text-[10px] font-bold " + (b.callable ? "bg-slate-100 text-slate-600 border border-slate-200" : "bg-slate-100 text-slate-600 border border-slate-200")}>{b.callable ? "Call" : "Bullet"}</span></td></tr>))}</tbody>
            </table>
          </div>
        </div>
        <div className="bg-slate-50 px-6 py-4 flex justify-end shrink-0 border-t border-slate-200"><button onClick={onClose} className="px-6 py-2 bg-slate-800 text-white rounded-xl text-xs font-bold hover:bg-slate-700 transition-all shadow-sm">Zurück</button></div>
      </div>
    </div>
  );
}
